<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="Automation Test"
           tests="7"
           failures="1"
           errors="0"
           skipped="0"
           time="102.401">
  <properties />
            <testcase name="verifyThatUserShouldLogInSuccessFullyWithValidCredentials" time="19.130" classname="com.automation.testsuite.SignPageTest">
                <failure type="java.lang.AssertionError"
                  message="The following asserts failed:
	not navigate to sign in page expected [sign out] but found [Sign out]"
              >
<![CDATA[java.lang.AssertionError: The following asserts failed:
	not navigate to sign in page expected [sign out] but found [Sign out]
  org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:46)
  org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:30)
  com.automation.testsuite.SignPageTest.verifyThatUserShouldLogInSuccessFullyWithValidCredentials(SignPageTest.java:53)
  sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  java.lang.reflect.Method.invoke(Method.java:498)
  org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:135)
  org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:673)
  org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:220)
  org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
  org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:945)
  org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:193)
  org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
  org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
  java.util.ArrayList.forEach(ArrayList.java:1249)
  org.testng.TestRunner.privateRun(TestRunner.java:808)
  org.testng.TestRunner.run(TestRunner.java:603)
  org.testng.SuiteRunner.runTest(SuiteRunner.java:429)
  org.testng.SuiteRunner.runSequentially(SuiteRunner.java:423)
  org.testng.SuiteRunner.privateRun(SuiteRunner.java:383)
  org.testng.SuiteRunner.run(SuiteRunner.java:326)
  org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
  org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
  org.testng.TestNG.runSuitesSequentially(TestNG.java:1249)
  org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
  org.testng.TestNG.runSuites(TestNG.java:1092)
  org.testng.TestNG.run(TestNG.java:1060)
  com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
  com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109)
]]>
      </failure>

          </testcase>
  
  
            <testcase name="verifyTheErrorMessageWithInValidCredentials" time="13.821" classname="com.automation.testsuite.SignPageTest" />
                <testcase name="verifyTheErrorMessageWithInValidCredentials" time="13.861" classname="com.automation.testsuite.SignPageTest" />
                <testcase name="userShouldNavigateToSignInPageSuccessFully" time="3.067" classname="com.automation.testsuite.SignPageTest" />
                <testcase name="verifyThatUserShouldLogOutSuccessFully" time="20.245" classname="com.automation.testsuite.SignPageTest" />
                <testcase name="verifyTheErrorMessageWithInValidCredentials" time="17.479" classname="com.automation.testsuite.SignPageTest" />
                <testcase name="verifyTheErrorMessageWithInValidCredentials" time="14.798" classname="com.automation.testsuite.SignPageTest" />
      
</testsuite>
